### ISSUE TITLE
Add some padding to the placeholder in the Newsletter container in Footer

### ISSUE THREAD

**Issue by patfire12345** [patfire12345/cerulean#34]
<img width="359" alt="image" src="https://github.com/patfire12345/cerulean/assets/60910369/f70dba10-8ea1-4eaa-8500-f7525189b11f">

**Comment by bilalshaikh292** [comment]
heyy @patfire12345 Is the Issue Still open I would like to contribute?

**Comment by patfire12345** [comment]
Resolved as of #43.
